language: csharp
solution: ReportUnit.sln
branches:
  only:
    - master

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
  - nuget restore ReportUnit.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory NUnitRunner

script:
  - xbuild /p:Configuration=Release ReportUnit.sln
  - mono ./NUnitRunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./ReportUnitTest/bin/Release/ReportUnitTest.dll
