language: csharp
solution: ReportUnit.sln
branches:
  only:
  - master

addons:
  apt:
    packages:
    - oracle-java8-set-default

install:
- nuget restore ReportUnit.sln
- nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory NUnitRunner

script:
- xbuild /p:Configuration=Release ReportUnit.sln
- mono ./NUnitRunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./ReportUnitTest/bin/Release/ReportUnitTest.dll

deploy:
  provider: releases
  api_key:
    secure: I6X08k+DRR8Cni3+8qRnbkwYnAX/xJZGs6GtH7RmqyBQJgs8tJvgGm8X3BTsDLDX1v3lPB1CrODapnKJ+tV0/21sHOSFAGFuOIuMRO0O4W4FKPOa9jZsWav0TpYa0gFtIOkziNcz9d4JaGFsvY5S5aS3MeYYhyMAY/RPD3M4HRq3+BlelNR+h3mw2HZMLiBgAVOYqn0tOQKlC+u1E6saTkpw4rBPcGSxyKbBIJAu1c5s0XNSKNhZOMRcmyEqh8/8P6QsOh+7UJWfbC0ePBkitG+KRwgypGSiEm5OqA5cJmRtza5JlknkWVw5E19gaWYKjlyGX81R4NwcygCdEtBitq6O7dUAGmQzFjeZe569BMN8yzUifdVHPVSrMwviv4rJ01ZvMhayDB6RfDrOnvMpMetQguIL7dlvUKBlNms/bsSyarMdNwBMxugZu+wxM6PdS3G3PRjjMUcUt+ZLXNMx/ghGxalyDuHyQ19f6RfqqSWR0iVAFTM+ngT2ViEQAKiEM5ugWLze5ebq+4rKi41tMDBB+TGI1Vce+afZJ9Iadsc7OtXAkY6WqP+K1NAX86JhoOpdAWjr9/i3yJo49D+sIQoN4FNZMl3oU/4/K7B6n+K08XTZULc3s+oXy5NHANtKhGxkWtSWRs5yJK0nR/0z/DsKXgULAA7+WMOrf9D7Wok=
  file: "$TRAVIS_BUILD_DIR/ReportUnit/bin/Release/ReportUnit.exe"
  on:
    tags: true
    repo: Artum/reportunit
