language: csharp
solution: ReportUnit.sln
branches:
  only:
    - master
    
install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory NUnitRunner

script:
  - xbuild /p:Configuration=Release ReportUnit.sln
  - mono ./NUnitRunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ReportUnitTest/bin/Release/ReportUnitTest.dll
