version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

platform:
  - Any CPU

configuration:
  - Debug
  - Release

build:
  project: ReportUnit.sln
  parallel: true
  verbosity: quiet
after_build:
  - nunit3-console .\ReportUnitTest\bin\Release\ReportUnitTest.dll --result=ReportUnitTestResults.xml;format=AppVeyor