version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore

platform:
  - Any CPU

configuration:
  - Release

build:
  project: ReportUnit.sln
  parallel: true
  verbosity: quiet

after_build:
  - nunit3-console .\ReportUnitTest\bin\$(configuration)\ReportUnitTest.dll --result=ReportUnitTestResults.xml;format=AppVeyor

deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: reportunit-latest-build
  auth_token:
    secure: aF0fLLmz97WNRikUBXRnLxJVJIn7sb7+h0uUH21d4S6zdAB0lfv3JGE5xPbcmUl6
  artifact: ReportUnit\bin\$(configuration)
  draft: true
  prerelease: true
  force_update: true