version: 0.2.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

skip_tags: true
test: off

before_build:
  - nuget restore

platform:
  - Any CPU

configuration:
  - Release

build:
  project: ReportUnit.sln
  parallel: true
  verbosity: quiet

after_build:
  - nunit3-console .\ReportUnitTest\bin\Release\ReportUnitTest.dll --result=ReportUnitTestResults.xml;format=AppVeyor

artifacts:
  - path: ReportUnit\bin\ReportUnit.exe
    name: ReportUnit-0.2.x
    type: zip
  
deploy:
- provider: GitHub
  tag: latest-build
  release: reportunit-latest-build
  auth_token:
    secure: aF0fLLmz97WNRikUBXRnLxJVJIn7sb7+h0uUH21d4S6zdAB0lfv3JGE5xPbcmUl6
  artifact: ReportUnit-0.2.x
  draft: false
  prerelease: true
  force_update: true